[package]
name = "survival-rogue-like"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.1"
bevy_asset_loader = "0.14.1"
ron = "0.7.0"
serde = "1.0.136"
rand = "0.8.5"
bevy_ecs_tilemap = "0.9.0"
noise = "0.8.2"
